In [7]:
import numpy as np

listNum = np.array([1, 2, 3])

print("Tipe : ", type(listNum))
print("Index ke 0 : ", listNum[0])

Tipe :  <class 'numpy.ndarray'>
Index ke 0 :  1


In [9]:
listNestedNum = np.array([[1,2,3], [4,5,6]])

print("Tipe : ", type(listNestedNum))
print("Matriks : ", listNestedNum.shape)
print("Index ke 0, 2 : ", listNestedNum[0][2])

Tipe :  <class 'numpy.ndarray'>
Matriks :  (2, 3)
Index ke 0, 2 :  3


In [26]:
listZerosNum = np.zeros((2,3))
listOnesNum = np.ones((2,3))
listEmptyNum = np.empty((2,4))
listArageNum = np.arange(0, 10, 2) #(start, stop, step)
print("Zero")
print(listZerosNum)
print()
print("Ones")
print(listOnesNum)
print()
print("Empty")
print(listEmptyNum)
print()
print("Arage")
print(listArageNum)

Zero
[[0. 0. 0.]
 [0. 0. 0.]]

Ones
[[1. 1. 1.]
 [1. 1. 1.]]

Empty
[[4.68155856e-310 0.00000000e+000 6.79038654e-313 2.22809558e-312]
 [2.14321575e-312 2.46151512e-312 2.41907520e-312 5.97819431e-322]]

Arage
[0 2 4 6 8]


In [129]:
listNum = np.array([1, 2, 3])

print("List")
print(listNum)

listNum = np.append(listNum, [4,5])
print()
print("List Append")
print(listNum)

listNum = np.delete(listNum, 1) #(index ke..)
print()
print("List Delete")
print(listNum)

listNum = np.insert(listNum, 0, 300) #(array, index ke .., value)
print()
print("List Insert")
print(listNum)

listNum = np.sort(listNum)
print()
print("List Sort")
print(listNum)

listNestedNum = np.array([[1,2,3], [4,5,6]])
print("List")
print(listNestedNum)

print()
print("List Ndim")
print(np.ndim(listNestedNum)) #banyaknya row / dimensi

print()
print("List Size")
print(np.size(listNestedNum)) #banyaknya elemen

print()
print("List Shape")
print(np.shape(listNestedNum))#banyaknya matriks

print()
print("List ReShape")
print(np.reshape(1, 1))#banyaknya matriks

List
[1 2 3]

List Append
[1 2 3 4 5]

List Delete
[1 3 4 5]

List Insert
[300   1   3   4   5]

List Sort
[  1   3   4   5 300]
List
[[1 2 3]
 [4 5 6]]

List Ndim
2

List Size
6

List Shape
(2, 3)

List ReShape
[1]

List Transpose
[  1   3   4   5 300]


In [60]:
listNum = np.array([1, 2, 3])

print("List")
print(listNum)

listNum1 = listNum[np.newaxis]
print()
print("List New Axis")
print(listNum1)

List
[1 2 3]

List New Axis
[[1 2 3]]


In [63]:
listNum = np.array([1, 2, 3])

print("List")
print(listNum)

listNum1 = np.expand_dims(listNum, axis=1)
print()
print("List Expand Dims")
print(listNum1)

List
[1 2 3]

List Expand Dims
[[1]
 [2]
 [3]]


In [127]:
listNum = np.array([1, 2, 3, 4, 5])

print("List")
print(listNum)

print()
print("Slice 0 s/d 2")
print(listNum[0:2])

print()
print("Slice start dari 3 s/d abis")
print(listNum[3])

listNestedNum = np.array([[1,2,3], 
                          [4,5,6], 
                          [7,8,9]])
print("List Nested")
print(listNestedNum)

print()
print("Slice value more than 3")
print(listNestedNum[listNestedNum > 3])

conditionMore = (listNestedNum >= 7)
conditionLess = (listNestedNum < 8)
conditionEqual = (listNestedNum == 3)
print()
print("Slice value more than equal 7")
print(listNestedNum[condition])
print()
print("Slice value more than equal 7 and less than 8")
print(listNestedNum[conditionMore & conditionLess])
print()
print("Slice value equal 3 or less than 8")
print(listNestedNum[conditionEqual | conditionLess])
print()
print("Slice value row 1 column 2")
print(listNestedNum[1,2]) #row, column

List
[1 2 3 4 5]

Slice 0 s/d 2
[1 2]

Slice start dari 3 s/d abis
4
List Nested
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Slice value more than 3
[4 5 6 7 8 9]

Slice value more than equal 7
[7 8 9]

Slice value more than equal 7 and less than 8
[7]

Slice value equal 3 or less than 8
[1 2 3 4 5 6 7]

Slice value row 1 column 2
6


In [90]:
a = np.array([[1,1],
              [2,2]])
b = np.array([[3,3],
              [4,4]])
print("List A")
print(a)
print("List B")
print(b)

print()
print("Merge Array Vetikal")
print(np.vstack((a, b)))

print()
print("Merge Array Horizontal")
print(np.hstack((a, b)))

List A
[[1 1]
 [2 2]]
List B
[[3 3]
 [4 4]]

Merge Array Vetikal
[[1 1]
 [2 2]
 [3 3]
 [4 4]]

Merge Array Horizontal
[[1 1 3 3]
 [2 2 4 4]]


In [105]:
listNum = np.array([1,2,3,5,6,7,8,9,10])
print("List")
print(listNum)

print()
print("Array Horizontal Split")
print(np.hsplit(listNum, 3)) #harus dibagi sama rata

List
[ 1  2  3  5  6  7  8  9 10]

Array Horizontal Split
[array([1, 2, 3]), array([5, 6, 7]), array([ 8,  9, 10])]


In [107]:
listNestedNum = np.array([[1,2,3], 
                          [4,5,6], 
                          [7,8,9]])
print("List Nested")
print(listNestedNum)

print()
print("Array Vetikal Split")
print(np.hsplit(listNestedNum, 3))

copyList = listNestedNum.copy()
print()
print("Copy Array")
print(copyList)

List Nested
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array Vetikal Split
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]

Copy Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [119]:
listNum = np.array([1,2,3,5,6,7,8,9,10])
print("List")
print(listNum)

print()
print("Sum")
print(listNum.sum())

print()
print("Min")
print(listNum.min())

print()
print("Max")
print(listNum.max())

print()
print("Mead")
print(listNum.mean())

listNestedNum = np.array([[1,2,3], 
                          [4,5,6], 
                          [7,8,9]])

print()
print("List Nested")
print(listNestedNum)

print()
print("Sum Per Kolom")
print(listNestedNum.sum(axis=0))

print()
print("Sum Per Baris")
print(listNestedNum.sum(axis=1))

List
[ 1  2  3  5  6  7  8  9 10]

Sum
51

Min
1

Max
10

Mead
5.666666666666667

List Nested
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum Per Kolom
[12 15 18]

Sum Per Baris
[ 6 15 24]


In [112]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Penjuamlahan Array per index")
print(a + b)

print()
print("Perkalian")
print(a * b)

print()
print("Pembagian")
print(a / b)

Penjuamlahan Array per index
[5 7 9]

Perkalian
[ 4 10 18]

Pembagian
[0.25 0.4  0.5 ]


In [120]:
listNum = np.array([1,2,3,5,6,7,8,9,10])
print("List")
print(listNum)

print()
print("Broadcasting")
print(listNum * 2)

List
[ 1  2  3  5  6  7  8  9 10]

Broadcasting
[ 2  4  6 10 12 14 16 18 20]


In [130]:
listNestedNum = np.array([[1,2,3], 
                          [4,5,6], 
                          [7,8,9]])

print()
print("List Nested")
print(listNestedNum)

print()
print("List Transpose")
print(listNestedNum.T)#baris -> kolom, kolom -> baris


List Nested
[[1 2 3]
 [4 5 6]
 [7 8 9]]

List Transpose
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [136]:
data = np.random.random((4,3,2))

print("List")
print(data)

print()
print("List Flatten")
print(data.flatten()) #merubah dari banyak dimensi menjadi 1 dimensi

List
[[[0.75129348 0.5584073 ]
  [0.59513365 0.32970166]
  [0.97439767 0.36796871]]

 [[0.48228706 0.68159011]
  [0.12787176 0.42419363]
  [0.57760565 0.30983932]]

 [[0.94982924 0.70088011]
  [0.56469179 0.21923665]
  [0.9047315  0.03974293]]

 [[0.35234755 0.52445986]
  [0.18320799 0.20743943]
  [0.9110566  0.33699729]]]

List Flatten
[0.75129348 0.5584073  0.59513365 0.32970166 0.97439767 0.36796871
 0.48228706 0.68159011 0.12787176 0.42419363 0.57760565 0.30983932
 0.94982924 0.70088011 0.56469179 0.21923665 0.9047315  0.03974293
 0.35234755 0.52445986 0.18320799 0.20743943 0.9110566  0.33699729]
